version: '2'
services:
  consul:
    image: "progrium/consul:latest"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap -ui-dir /ui"
  nitro-gateway:
    container_name: "nitro-gateway"
    hostname: "nitro-gateway"
    build:
      context: .
      dockerfile: docker/nitro-gateway/Dockerfile
    links:
      - consul
    ports:
      - "3100:3100"
